# Generated by Django 3.1 on 2024-01-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dejavu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='noveldetail',
            name='user_id',
            field=models.UUIDField(),
        ),
    ]
