# Generated by Django 3.1 on 2024-01-12 15:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dejavu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='novel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dejavu_app.noveldetail', verbose_name='対象小説'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
