# Generated by Django 3.1 on 2023-12-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dejavu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novels',
            name='status',
            field=models.IntegerField(choices=[(1, '承'), (2, '転'), (3, '結')], default=1),
        ),
    ]
