# Generated by Django 3.1 on 2024-01-17 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dejavu_app', '0002_auto_20240112_1522'),
        ('dejavu_app', '0002_auto_20240117_0614'),
    ]

    operations = [
    ]
