# Generated by Django 3.1 on 2023-12-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dejavu_app', '0002_novels_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novels',
            name='status',
            field=models.IntegerField(choices=[(0, '承'), (1, '転'), (2, '結')], default=0),
        ),
    ]
