# Generated by Django 3.2.23 on 2023-12-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dejavu_app', '0002_auto_20231220_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noveldetail',
            name='novel_master_id',
            field=models.IntegerField(choices=[(1, 'Development'), (2, 'Turn'), (3, 'Conclusion')], default=1),
        ),
        migrations.AlterField(
            model_name='novelmaster',
            name='status',
            field=models.IntegerField(choices=[(1, 'Development'), (2, 'Turn'), (3, 'Conclusion')], default=1),
        ),
    ]
