# Generated by Django 3.1 on 2024-01-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dejavu_app', '0003_merge_20240117_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user_id',
            field=models.UUIDField(),
        ),
    ]
