# Generated by Django 3.2.23 on 2023-12-24 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dejavu_app', '0003_auto_20231222_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novels',
            name='user_id',
        ),
        migrations.AddField(
            model_name='novels',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
