# Generated by Django 3.2.23 on 2023-12-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dejavu_app', '0004_auto_20231224_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='novels',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
