# Generated by Django 3.1 on 2023-12-30 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dejavu_app', '0004_auto_20231230_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novel_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novel_master_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('novel_id', models.IntegerField()),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='novel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dejavu_app.novel_detail', verbose_name='対象小説'),
        ),
    ]
