# Generated by Django 3.1 on 2023-12-30 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dejavu_app', '0005_auto_20231230_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('postdate', models.DateField(auto_now_add=True, verbose_name='投稿日')),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comments',
            name='novel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dejavu_app.test_blog', verbose_name='対象小説'),
        ),
        migrations.DeleteModel(
            name='Novel_detail',
        ),
    ]
