# Generated by Django 3.1 on 2023-12-31 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dejavu_app', '0006_auto_20231230_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='novel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dejavu_app.noveldetail', verbose_name='対象小説'),
        ),
        migrations.DeleteModel(
            name='Test_blog',
        ),
    ]
