# Generated by Django 3.2.23 on 2023-12-24 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dejavu_app', '0007_rename_user_novels_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novels',
            old_name='user_id',
            new_name='user',
        ),
    ]
