# Generated by Django 3.2.23 on 2023-12-24 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dejavu_app', '0009_alter_novels_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novels',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
