version: '3'

services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dejavu-db
      MYSQL_USER: dejavu
      MYSQL_PASSWORD: dejavu
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    healthcheck:
      test: "mysqladmin -h127.0.0.1 -P3306 -uroot -proot ping"
      interval: 1s
      timeout: 3s
      retries: 10

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
