blank_issues_enabled: true
contact_links:
  - name: Add new ToDo
    about: made by config.yml
    # edit {username} and {repo} for your environment
    url: https://github.com/takuma-shishido/dejavu/issues/new?template=custom.md&projects=takuma-shishido%2Fdejavu%2F1&labels=dejavu